version: '3.8'

services:
  db:
    image: postgres:17
    container_name: vacancy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vacancy_service
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vacancy_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    container_name: vacancy_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend